name: delproxy

on:
  workflow_dispatch:

    
jobs:
  Fork-Filter-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4.1.0
        with:
          repository: SouthAlley/ca
          path: ca-repo

      - name: 下载文件到 Surge
        run: |      
           declare -A file_path_url=(
                 ["MyBlockAds.list"]="surge/rule/ad/del.ini https://raw.githubusercontent.com/RuCu6/QuanX/main/Rules/MyBlockAds.list"
                 ["StreamingRule.list"]="Surfboard/rule/attach/del.ini https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/filter/fenliuxiuzheng.list"
                 ["AnotherRule.list"]="surge/rule/del.ini https://raw.githubusercontent.com/RuCu6/QuanX/main/Rules/MyBlockAds.list"
           )

           for file in "${!file_path_url[@]}"; do
               IFS=' ' read -r path url <<< "${file_path_url[$file]}"
               mkdir -p "ca-repo/${path%/*}"
               curl -L -o "ca-repo/$path" "$url"

               if [ -e "ca-repo/$path" ]; then
                  # 修改逗号为单独的逗号
                  sed -i 's/, /,/g' "$file"
                  # 替换 host 为 DOMAIN，忽略大小写
                  sed -i -e 's/host,/DOMAIN,/gi' "$file"
                  sed -i -e 's/host-suffix,/DOMAIN-SUFFIX,/gi' "$file"
                  sed -i -e 's/host-keyword,/DOMAIN-KEYWORD,/gi' "$file"
                  sed -i 's/ip-cidr,/IP-CIDR,/gi' "$file"
                  sed -i 's/ip6-cidr,/IP-CIDR6,/gi' "$file"
                  sed -i 's/user-agent,/USER-AGENT,/g' "$file"
                  # 删除不必要的部分
                  sed -i 's/\([^,]*,[^,]*\),.*/\1/g' "$file"
                  # 如果包含 IP-CIDR 且不包含 no-resolve 则添加 no-resolve
                  sed -i '/IP-CIDR/ {/no-resolve/! s/$/,no-resolve/}; /IP-CIDR6/ {/no-resolve/! s/$/,no-resolve/}' "$file"
                  # 删除分号
                  sed -i 's/;//g' "$file"
                  # 删除注释
                  sed -i 's/#.*//' "$file"
                  # 删除空行
                  sed -i '/^[[:space:]]*$/d' "$file"
  
                  # 根据文件路径判断是 surge 还是 surfboard，并删除相应规则
                  if [[ "$path" == *"Surfboard"* ]]; then
                    sed -i '/^\(URL-REGEX\|USER-AGENT\|OR\|AND\),.*$/d'
                  fi
               else
                  echo "ca-repo/rule/$path 未找到。"
               fi
           done


      - name: Add and Commit changes
        run: |
          cd ca-repo
          if [[ -n $(git status -s) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add "surge/rule/*" "Surfboard/rule/*"
            git commit -m "Update rules"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi



          
